name: Build and Deploy

on:
  push:
    branches: [ main, zola ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true  # Fetch Hugo themes
        
    - name: Setup Zola
      uses: taiki-e/install-action@v2
      with:
        tool: zola@0.18.0
    
    - name: Build site
      run: zola build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: public
        path: public/
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/zola'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: public
        path: public/
    
    - name: Deploy to Google Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: fashionunited-docs
        region: europe-west1
        source: .
        env_vars: |
          NODE_ENV=production