# options:
#   logging: CLOUD_LOGGING_ONLY
#   pool: {}
projectId: developers-fashionunited-com
steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - europe-west1-docker.pkg.dev/$PROJECT_ID/developer-docs/astro
      - --builder
      - gcr.io/buildpacks/builder:latest
      - --cache-image
      - europe-west1-docker.pkg.dev/$PROJECT_ID/developer-docs/astro-cache:latest
      - --publish
  - id: Deploy production Cloud Run
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - developer-docs
      - --image=europe-west1-docker.pkg.dev/$PROJECT_ID/developer-docs/astro:latest
      - --region=europe-west1
    timeout: "1600s"
